#pragma once

#include <array>
#include <cstdint>
#include <optional>
#include <string>
#include <string_view>

#include "EnumHelpers.hpp"

namespace SlLib::Enums {

enum class TriggerPhantomHashInfo : std::int32_t
{
    Empty = 0,
    AirBoost = 189157517,
    BoostPad = -2042409423,
    BoatBoostGate = 125346184,
    TransformCar = -841982324,
    TransformPlane = 118760201,
    TransformBoat = 210079875,
    LandPlane = -1876715491,
    SpinOut = -1213970453,
    SpinOutHeavy = 870623274,
    SecondaryWeaponEffect = -1540354832,
    Respot = -1558689353,
    MineExplosionFX = 1952503777,
    Explosion = 1070353362,
    Squash = 1498295247,
    SquashHeavy = -1420524006,
    SlowdownShunt = -696405373,
    SlowdownShuntLight = -1383978361,
    FillWater = -226110868,
    HideNode = 709647355,
    ShowNode = 469498329,
    EnableNode = -1384115316,
    DisableNode = -37455467,
    ForceTransformCar = -317693437,
    PlayAudio = 1759330814,
    FadeAudio = -1544848447,
    PlayAnimationLink = 1540381204,
    CameraShake = 2101732718,
    TriggerParticleLink = -733180385,
    ScreenSplash = -398790126,
    CollectAnObject = 1568854034,
    DropAnObject = -320711608,
    Teleport = 1084257758,
    TimedTeleport = 994238613,
    TargetSmash = -1048956908,
    SwitchToCarRoute = 1302463695,
    SwitchToBoatRoute = 691702127,
    SwitchToPlaneRoute = -459876044,
    SwitchToExclusiveCarRoute = 1200708874,
    SwitchToExclusiveBoatRoute = -558361262,
    SwitchToExclusivePlaneRoute = 1829363952,
    AiObstacle = -1125608476,
    AiGenericTarget = -1806459307,
    EnableRacingLines = 1771726842,
    DisableRacingLines = 317789545,
    EnableRacingLinesPermanently = -1739858317,
    DisableRacingLinesPermanently = 931038684,
    SwitchToOpenRoute = -760816338,
    TransformCarPrompt = 891162648,
    TransformBoatPrompt = 823031447,
    TransformPlanePrompt = 1700585297,
    AudioSwoosh_SmallObject_Pan = -1760910791,
    AudioSwoosh_MediumObject_Pan = -1445879522,
    AudioSwoosh_LargeObject_Pan = 1194761607,
    AudioSwoosh_SmallObject_Center = 15450130,
    AudioSwoosh_MediumObject_Center = 307414316,
    AudioSwoosh_LargeObject_Center = -1418509929,
    AudioSwoosh_EnterTunnel = 524898988,
    AudioSwoosh_ExitTunnel = -1331351440,
    Cameo_EnableSplineMovement = -40143073,
    EnableTag = 581302922,
    DisableTag = -377967812,
    TransformRespot = -2048107817,
    NightsRing = 1994748133,
    NightsRingFinal = 312533218,
    ForceLap1 = -1875627780,
    ForceLap2 = 2079250086,
    ForceLap3 = 1674309033,
    TriggerNode = 329379503,
    Electrify_LightSlowdown = 1227761862,
    Electrify_HeavySlowdown = 75749318,
    TriggerLightSet1 = 324923854,
    TriggerLightSet2 = -1526649043,
    TriggerLightSet3 = -1996236308,
    EnableForRacerViewport = 1667948044,
    DisableForRacerViewport = 55470186,
    ForceTriggerPhantom = -260391570,
};

inline constexpr auto allTriggerPhantomHashInfos() noexcept -> std::array<TriggerPhantomHashInfo, 77>
{
    return {TriggerPhantomHashInfo::Empty,
            TriggerPhantomHashInfo::AirBoost,
            TriggerPhantomHashInfo::BoostPad,
            TriggerPhantomHashInfo::BoatBoostGate,
            TriggerPhantomHashInfo::TransformCar,
            TriggerPhantomHashInfo::TransformPlane,
            TriggerPhantomHashInfo::TransformBoat,
            TriggerPhantomHashInfo::LandPlane,
            TriggerPhantomHashInfo::SpinOut,
            TriggerPhantomHashInfo::SpinOutHeavy,
            TriggerPhantomHashInfo::SecondaryWeaponEffect,
            TriggerPhantomHashInfo::Respot,
            TriggerPhantomHashInfo::MineExplosionFX,
            TriggerPhantomHashInfo::Explosion,
            TriggerPhantomHashInfo::Squash,
            TriggerPhantomHashInfo::SquashHeavy,
            TriggerPhantomHashInfo::SlowdownShunt,
            TriggerPhantomHashInfo::SlowdownShuntLight,
            TriggerPhantomHashInfo::FillWater,
            TriggerPhantomHashInfo::HideNode,
            TriggerPhantomHashInfo::ShowNode,
            TriggerPhantomHashInfo::EnableNode,
            TriggerPhantomHashInfo::DisableNode,
            TriggerPhantomHashInfo::ForceTransformCar,
            TriggerPhantomHashInfo::PlayAudio,
            TriggerPhantomHashInfo::FadeAudio,
            TriggerPhantomHashInfo::PlayAnimationLink,
            TriggerPhantomHashInfo::CameraShake,
            TriggerPhantomHashInfo::TriggerParticleLink,
            TriggerPhantomHashInfo::ScreenSplash,
            TriggerPhantomHashInfo::CollectAnObject,
            TriggerPhantomHashInfo::DropAnObject,
            TriggerPhantomHashInfo::Teleport,
            TriggerPhantomHashInfo::TimedTeleport,
            TriggerPhantomHashInfo::TargetSmash,
            TriggerPhantomHashInfo::SwitchToCarRoute,
            TriggerPhantomHashInfo::SwitchToBoatRoute,
            TriggerPhantomHashInfo::SwitchToPlaneRoute,
            TriggerPhantomHashInfo::SwitchToExclusiveCarRoute,
            TriggerPhantomHashInfo::SwitchToExclusiveBoatRoute,
            TriggerPhantomHashInfo::SwitchToExclusivePlaneRoute,
            TriggerPhantomHashInfo::AiObstacle,
            TriggerPhantomHashInfo::AiGenericTarget,
            TriggerPhantomHashInfo::EnableRacingLines,
            TriggerPhantomHashInfo::DisableRacingLines,
            TriggerPhantomHashInfo::EnableRacingLinesPermanently,
            TriggerPhantomHashInfo::DisableRacingLinesPermanently,
            TriggerPhantomHashInfo::SwitchToOpenRoute,
            TriggerPhantomHashInfo::TransformCarPrompt,
            TriggerPhantomHashInfo::TransformBoatPrompt,
            TriggerPhantomHashInfo::TransformPlanePrompt,
            TriggerPhantomHashInfo::AudioSwoosh_SmallObject_Pan,
            TriggerPhantomHashInfo::AudioSwoosh_MediumObject_Pan,
            TriggerPhantomHashInfo::AudioSwoosh_LargeObject_Pan,
            TriggerPhantomHashInfo::AudioSwoosh_SmallObject_Center,
            TriggerPhantomHashInfo::AudioSwoosh_MediumObject_Center,
            TriggerPhantomHashInfo::AudioSwoosh_LargeObject_Center,
            TriggerPhantomHashInfo::AudioSwoosh_EnterTunnel,
            TriggerPhantomHashInfo::AudioSwoosh_ExitTunnel,
            TriggerPhantomHashInfo::Cameo_EnableSplineMovement,
            TriggerPhantomHashInfo::EnableTag,
            TriggerPhantomHashInfo::DisableTag,
            TriggerPhantomHashInfo::TransformRespot,
            TriggerPhantomHashInfo::NightsRing,
            TriggerPhantomHashInfo::NightsRingFinal,
            TriggerPhantomHashInfo::ForceLap1,
            TriggerPhantomHashInfo::ForceLap2,
            TriggerPhantomHashInfo::ForceLap3,
            TriggerPhantomHashInfo::TriggerNode,
            TriggerPhantomHashInfo::Electrify_LightSlowdown,
            TriggerPhantomHashInfo::Electrify_HeavySlowdown,
            TriggerPhantomHashInfo::TriggerLightSet1,
            TriggerPhantomHashInfo::TriggerLightSet2,
            TriggerPhantomHashInfo::TriggerLightSet3,
            TriggerPhantomHashInfo::EnableForRacerViewport,
            TriggerPhantomHashInfo::DisableForRacerViewport,
            TriggerPhantomHashInfo::ForceTriggerPhantom};
}

std::string toString(TriggerPhantomHashInfo hashInfo);

template <>
std::optional<TriggerPhantomHashInfo> fromString<TriggerPhantomHashInfo>(std::string_view text);

inline std::optional<TriggerPhantomHashInfo> fromStringTriggerPhantomHashInfo(std::string_view text)
{
    return fromString<TriggerPhantomHashInfo>(text);
}

} // namespace SlLib::Enums
